### ISSUE TITLE
How to set zero lookup rate?

### ISSUE THREAD

**Issue by WangTingZheng** [ls4154/YCSB-cpp#14]
The meaning of "zero look rate" is the proportion of keys in queries that are not present in the database during the query process, Some paper, such as Elasticbf need this.

**Comment by ls4154** [comment]
Since YCSB performs transactions (update, read) only for already inserted keys, zero lookup is not supported. But it can be achieved by using a higher `recordcount` in the run phase than recordcount used in the load phase.

Adding that feature might not be difficult. However, from what I have read, the elasticbf paper simply presents zero lookup ratio. In order to implement it, we need information about the distribution of non-existent keys.
